### ISSUE TITLE
Method put nog working

### ISSUE THREAD

**Issue by vrgenl** [laracasts/Behat-Laravel-Extension#4] opened 2015-01-19 09:31 UTC
Hi Jeff,

I've noticed that all my forms that post with the _method PUT are handled as normal POST requests and won't hit $router->put. I've got the same tests setup with Codeception and thats working just fine.

Do you have any idea how this is possible?

Kind regards,

Rogier

**Comment by JeffreyWay** [comment] 2015-01-19 13:47
Hmm - that's really weird. 

Tough to say, without seeing your form code and the related route registration.

**Comment by vrgenl** [comment] 2015-01-22 21:18
Ill try to explain my setup.

routes.php

``` php
$router->get('account/password/retrieve', ['as' => 'retrieve.create', 'uses' => 'RetrievePasswordController@create']);
$router->post('account/password', ['as' => 'retrieve.store', 'uses' => 'RetrievePasswordController@store']);
$router->get('account/password/reset/{token}', ['as' => 'retrieve.edit', 'uses' => 'RetrievePasswordController@edit']);
$router->put('account/password', ['as' => 'retrieve.update', 'uses' => 'RetrievePasswordController@update']);
```

Blade template
`{!! Form::open(['route' => 'retrieve.update', 'method' => 'put']) !!}`

printLastResponse() output:

``` html
<form method="POST" action="http://localhost:8000/account/password" accept-charset="UTF-8">
    <input name="_method" type="hidden" value="PUT">
</form>
```

If I run the test and I don't fill in the proper fields (for example password_confirmation) than I get the response from the retrieve.store.

**Comment by jesseschutt** [comment] 2015-02-02 19:15
I've bumped into a similar scenario with `delete`. I get a MethodNotAllowedException when I printLastResponse().

**Comment by jschutt** [comment] 2015-02-02 19:26
@rogierverbrugge Have you figured out any solution?

**Comment by zhiyand** [comment] 2015-02-03 01:17
Same issue, `delete` results in `MethodNotAllowedException`

**Comment by jesseschutt** [comment] 2015-02-04 15:25
@JeffreyWay  - First off, thanks for putting this extension together! It's much appreciated.

Now that Laravel 5 is in the wild, is there a chance you could look in to this issue? Any forms that run anything other than POST do what @rogierverbrugge posted at the beginning of this issue. 

Thank you!

**Comment by vrgenl** [comment] 2015-02-04 19:11
So far I haven't found a solution. I'll try to walk through the package, maybe I will find something.

**Comment by svrnm** [comment] 2015-02-12 11:28
I had the same issue and I found a (first) solution: If you have a look at the public/index.php you will find the following: 

``` php
$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);
```

This method calls `enableHttpMethodParameterOverride`, which later will take care of changing the Method to "PUT". I fixed this by changing `LaravelBooter::boot()`:

``` php
$app->loadEnvironmentFrom($this->environmentFile());
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();
$app->make('Illuminate\Http\Request')->capture();
```

**Comment by acaron** [comment] 2015-02-18 21:14
+1 for @svrnm your solution is working! Indeed, Behat was probably trying to call a POST instead of a PUT since it was not yet changed. You should do a pull request!

**Comment by rudowastaken** [comment] 2015-02-22 14:24
I can confirm. @svrnm provided a working solution.

**Comment by RomainLanz** [comment] 2015-02-23 17:00
Thank you @svrnm, working fine.

**Comment by RomainLanz** [comment] 2015-03-01 19:48
@rogierverbrugge This is fixed by the PR above, you can close this issue. :)

**Closed as completed** 2015-03-09 14:07 UTC
